name: 'Hello World (Python Version)'
description: 'Greet the Earth. This is an example of an action using Python.'

# Define your inputs here.
inputs:
  who-to-greet:
    description: Who to greet
    required: true
    default: World

# Define your outputs here.
outputs:
  time:
    description: The time we greeted you

runs:
  using: "composite"
  steps:
    - run: if [[ -f ${{github.action_path}}/requirements.txt ]]; then pip install -r ${{github.action_path}}/requirements.txt >> /dev/null; fi
      shell: bash
    - run: if [[ -f ${{github.action_path}}/src/requirements.txt ]]; then pip install -r ${{github.action_path}}/src/requirements.txt; fi
      shell: bash
    - run: if [[ -f ${{github.action_path}}/src/requirements.txt ]]; then pip install -r ${{github.action_path}}/src/requirements.txt >> /dev/null; fi
      shell: bash
    - run: python ${{github.action_path}}/src/action.py
      shell: bash
